### ISSUE TITLE
Hard coded file location in cnv_seeds.py

### ISSUE THREAD

**Issue by mattjones315** [AmpliconSuite/CoRAL#4]
There is a hard-coded file location for centromeres in `cnv_seeds.py`, [here](https://github.com/AmpliconSuite/CoRAL/blob/43aef13a4ab5f667abcd23a46930f18ecdd5426b/src/cnv_seed.py#L48).

We should remove this line in favor of adding a new argument specifying the path to the centromeres bed.

**Comment by kyzhu** [comment]
Hi @mattjones315 can you check if the new code works?
